import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth, signOut } from "@/auth";
import { Button } from "@/components/ui/button";
import {Header} from "@/components/common/Header"
import {Footer} from "@/components/common/Footer"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        {!!session && (
          <form
            className="absolute top-8 right-8"
            action={async () => {
              "use server";
              await signOut();
            }}
          >
            <Button type="submit">Выйти</Button>
          </form>
        )}
        {children}
      </body>
    </html>
  );
}
